### ISSUE TITLE
broccoli-funnel update 0.2.12 breaks build

### ISSUE THREAD

**Issue by medokin** [yahoo/ember-intl#251] opened 2015-11-03 13:39 UTC
It seems like the broccoli-funnel update to 0.2.12 broke something.
Everythink works fine if I set broccoli-funnel to =<0.2.10

Steps to reproduce:

```bash
> ember new intl-test
> cd intl-test
> ember install ember-intl@2.0.0-rc.4 // actually it does not matter which version you take
> ember s


version: 1.13.8
Livereload server on http://localhost:49156
Serving on http://localhost:4200/
ENOENT: no such file or directory, mkdir 'c:\dev\ember\intl-test\tmp\funnel-outp
ut_path-Y4uJi6u4.tmp\assets\intl'
Error: ENOENT: no such file or directory, mkdir 'c:\dev\ember\intl-test\tmp\funn
el-output_path-Y4uJi6u4.tmp\assets\intl'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:799:18)
    at Funnel.applyPatch [as _applyPatch] (c:\dev\ember\intl-test\node_modules\e
mber-intl\node_modules\broccoli-funnel\index.js:287:10)
    at Funnel.<anonymous> (c:\dev\ember\intl-test\node_modules\ember-intl\node_m
odules\broccoli-funnel\index.js:246:10)
    at Array.forEach (native)
    at Funnel.processFilters (c:\dev\ember\intl-test\node_modules\ember-intl\nod
e_modules\broccoli-funnel\index.js:245:9)
    at Funnel.build (c:\dev\ember\intl-test\node_modules\ember-intl\node_modules
\broccoli-funnel\index.js:167:10)
    at c:\dev\ember\intl-test\node_modules\ember-intl\node_modules\broccoli-funn
el\node_modules\broccoli-plugin\read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (c:\dev\ember\intl-test\node_modules\ember-i
ntl\node_modules\broccoli-funnel\node_modules\broccoli-plugin\node_modules\promi
se-map-series\node_modules\rsvp\dist\rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (c:\dev\ember\intl-test\node_modules\e
mber-intl\node_modules\broccoli-funnel\node_modules\broccoli-plugin\node_modules
\promise-map-series\node_modules\rsvp\dist\rsvp.js:505:17)

```

**Comment by rwjblue** [comment] 2015-11-03 14:48
ember-intl is using `Funnel` to move a set of input files to `assets/intl` [here](https://github.com/yahoo/ember-intl/blob/master/index.js#L134-L138). The error is originating from https://github.com/broccolijs/broccoli-funnel/blob/master/index.js#L287.

I am not super familiar with fs-tree-diff (or the new refactor to use it) yet, but a complete guess is that calling `fs.mkdirSync` (as opposed to `mkdir -p`) isn't accounting for parent directories that do not exist yet?  

@stefanpenner - Any ideas on this?

**Comment by stefanpenner** [comment] 2015-11-03 15:59
let me try on posix, otherwise i'll need to debug on some windows machine.

**Comment by stefanpenner** [comment] 2015-11-03 16:12
Unfortunately unable to reproduce on OSX. 

> I am not super familiar with fs-tree-diff (or the new refactor to use it) yet, but a complete guess is that calling fs.mkdirSync (as opposed to mkdir -p) isn't accounting for parent directories that do not exist yet?

no fs-tree-diff takes this into account (or should be)  but i noticed the test suite does not explicity test this so I opened an issue and will investigate later today https://github.com/stefanpenner/fs-tree-diff/issues/9

**Comment by mm2ha** [comment] 2015-11-03 17:09
@stefanpenner I have the same exact error. I have moved my application to a new machine (Windows) and started to get this build error.

I have installed the ember cli windows addon, but unfortunately that did not help and the same error persists.

My colleagues were not getting this error a few weeks ago (on Windows as well) with Node v0.12.7, if that helps. But another one of my colleagues is getting the same error now with Node v4.2.1 (but on a new machine as well).

Please let me know if there is anything I can do to help you debug this issue.

**Comment by kellyselden** [comment] 2015-11-03 18:52
@stefanpenner I'm in training this week. If not resolved by the weekend, I can dig in.

**Comment by stefanpenner** [comment] 2015-11-03 19:17
> Please let me know if there is anything I can do to help you debug this issue.

i'll need to dig up a windows machine at work, or will have to look in detail tomorrow night (i have a machine at home, but will be speaking at an event tonight)

**Comment by srsgores** [comment] 2015-11-04 16:39
Yeah, also getting this on Windows.  Would like to see a solution at some point, as we only have Windows machines in the office.  I guess Docker will have to do for now?

**Comment by stefanpenner** [comment] 2015-11-04 18:03
@srsgores we will get it sorted out in the next day or so. I'll head home earlier today to use my windows machine before my evening plans.

For some reason getting a windows machine/vm at work is annoying, but i'l keep at it.

**Comment by stefanpenner** [comment] 2015-11-05 15:42
i made some notes here: https://github.com/broccolijs/broccoli-funnel/issues/53

Im going to work from home today, as I have a nice windows rig here. I hope to address this issue upstream by the end of the day.

**Comment by stefanpenner** [comment] 2015-11-10 19:58
I still need to test on windows (don't have one handy at work), but I believe https://github.com/joliss/node-walk-sync/pull/19 should address (or improve the situation)

```
npm ls walk-sync
> 0.2.6 
```

**Comment by manuelsalvatori** [comment] 2015-11-12 10:39
@stefanpenner the latest version is 0.2.6 so how could I have the 0.2.7? (https://github.com/joliss/node-walk-sync)
I still have the CI environment down, it's now 4 days and two dev machines broken.
Do you have any working solution you can suggest me?
My only option right now is to get rid of ember-intl.

**Comment by jasonmit** [comment] 2015-11-13 08:57
@manuelsalvatori looks like he meant 0.2.6

**Comment by manuelsalvatori** [comment] 2015-11-13 09:05
@jasonmit thanks, I guessed that but it means that it doesn't fix the problem.
I had to remove ember-intl, it's a shame but I could not find any other solution.

**Comment by CrshOverride** [comment] 2015-11-16 03:56
@manuelsalvatori We're currently developing our application inside a Vagrant Virtual Machine that runs Linux inside of Windows. By building inside the Linux VM, we work around the issue w/ building on Windows. It's less than ideal, but works.

@stefanpenner If there's anything specific you want tested on Windows, let me know. While we have working development machines, our build server is still running Windows so we're unable to build at the moment.

**Comment by jasonmit** [comment] 2015-11-16 07:12
@CrshOverride please try rc5.  I cannot validate the changes since I don't have a windows VM setup, but I've removed the use of path.join where interfacing with broccoli.

**Comment by stefanpenner** [comment] 2015-11-16 17:09
@CrshOverride can you provide an isolate example app demonstrating the issue, i can look tonight.

**Comment by CrshOverride** [comment] 2015-11-18 01:45
@jasonmit @stefanpenner It looks like the change introduced in `rc5` took care of the issue. Our build is succeeding once again.

**Comment by jasonmit** [comment] 2015-11-19 08:50
Excellent, thank you.  Closing the issue.

**Closed by jasonmit** 2015-11-19 08:50 UTC
Labels: dependency issue
