### ISSUE TITLE
Fix For recompute language in newer ember version

### ISSUE THREAD

**Issue by onceatime** [yahoo/ember-intl#150] opened 2015-07-06 21:44 UTC
starting @ verison 1.13 recompute the locale at runtime stops working to fix please add:

```
onIntlLocaleChanged: Ember.observer('intl.locale', function() {
  this.recompute();
}),
```

to ember-intl/addon/helpers/intl-get.js after intl: Ember.inject.service(), @ line 13.

sorry cant create a pull request right now.

**Comment by jasonmit** [comment] 2015-07-06 22:36
Good catch :+1: will fix and write a test

**Comment by jasonmit** [comment] 2015-07-06 23:26
@onceatime you're using ember-intl 2.0.0-beta - correct?

**Comment by onceatime** [comment] 2015-07-06 23:32
```
"ember-intl": "2.0.0-beta.6",
```
```
"ember": "2.0.0-beta.1",
```

but the problem starts @ember 1.13.0

**Comment by jasonmit** [comment] 2015-07-06 23:34
Thanks!  PR is opened which will resolve this.  Once merged, I'll version as beta.7.

**Comment by onceatime** [comment] 2015-07-06 23:41
thx. found out the same happens to date, numbers and so on... ( no rerender on locale change ).. i look into it if time left.

**Comment by jasonmit** [comment] 2015-07-06 23:46
I'm not sure that's the case for date, number, time, relative.  They all extend from the same helper and in the dummy app shows they're recomputing as expected.

If you can reproduce this and post a sample app, I'll be happy to investigate.

Also, which browser are you testing in?

**Comment by onceatime** [comment] 2015-07-06 23:51
any browser ( poly included )... the observer gets fired 'onIntlLocaleChanged' but no date gets to the compute function! Only the translations from get helper

**Comment by jasonmit** [comment] 2015-07-06 23:57
Can you post a dummy app showing this issue?  I'm not able to reproduce this with format-date and number both with static and computed properties arguments

**Comment by onceatime** [comment] 2015-07-07 00:00
sorry i cant... ( this is a client project. ) maybe it is because caching // ember observer... the date doesnt change at all! THe message changes because its coupled to the intl-get and oberver will fire. just a idea.

**Comment by jasonmit** [comment] 2015-07-07 00:00
Also, my tests were against 1.10.0-1.13.3. I only support >= 1.10.x <= 1.13.x at the moment

**Comment by onceatime** [comment] 2015-07-07 00:01
same happen in 1.13.x

**Comment by jasonmit** [comment] 2015-07-07 00:01
> sorry i cant... ( this is a client project. )

I meant to throw together a small app showcasing and isolating the issue.

**Comment by onceatime** [comment] 2015-07-07 00:03
ok give me a sec.

**Comment by onceatime** [comment] 2015-07-07 00:18
ok this was my fault! u right this only happens in the unstable ember 2.0.0 beta branch. here u can find the repo for later testing. https://github.com/onceatime/ember-intl-ember-2.0.0-beta.1-format-date

**Comment by jasonmit** [comment] 2015-07-07 00:34
Thanks!  Going to close this, beta.7 was published to npm.

**Closed by jasonmit** 2015-07-07 00:34 UTC
