### ISSUE TITLE
Using bound properties as message key

### ISSUE THREAD

**Issue by bakura10** [yahoo/ember-intl#54] opened 2015-02-21 14:41 UTC
Hi,

I have a component that generate keys, and I want to use those as bound properties in my template, but it seems it does not work. Here is my template:

```hbs
<li {{action 'setRange' range.from range.to}}>{{format-message (intl-get range.label)}}</li>
```

the "range.label" is a valid key that exists in my locale config, but I have a  Uncaught ReferenceError: Could not find Intl object: range.label error

Thanks!

**Comment by bakura10** [comment] 2015-02-21 14:41
NVM. It was in the doc. Stupid me.

**Comment by bakura10** [comment] 2015-02-21 14:43
I'm reopening, actually it does not seem to work. I've used it the same way as in the doc:

```hbs
{{format-message range.label}}
```

But it displays the key instead of translating it.

**Comment by jasonmit** [comment] 2015-02-21 14:50
Okay, I likely introduced this regression last week.  Will fix and cover with a test today.  Ember 1.9 or 1.10?

**Comment by bakura10** [comment] 2015-02-21 14:51
I'm using Ember 1.11.0-beta2 :)

**Comment by jasonmit** [comment] 2015-02-21 19:17
If range.label is a computed which returns a string literal, or is just a string literal this will work: `{{format-message range.label}}`

If range.label is a computed property which returns a message path then this will not work.  I'll need to update the documentation to be a bit more clear about that.  In any case, I will also update intl-get to handle this case of passing a computed property which returns a key to a message.  Though, it brings up an interesting issue about how do I know that what you're returning from your computed property is a path or a string literal, since they're both strings :)

**Comment by bakura10** [comment] 2015-02-21 20:06
In my case range.label returns a key string ("top_bar.date_selector.last_30_days" in my application). Here is my code that returns an object, and then inside a each, I use the "range.label":

```js
ranges: function() {
    var today = new Date(),
        day   = today.getDate(),
        month = today.getMonth(),
        year  = today.getFullYear();

    return [
      {label: 'metrics_top_bar.date_selector.today', from: today, to: today},
      {label: 'metrics_top_bar.date_selector.yesterday', from: new Date(year, month, day - 1), to: new Date(year, month, day - 1)},
      {label: 'metrics_top_bar.date_selector.last_7_days', from: new Date(year, month, day - 7), to: today},
      {label: 'metrics_top_bar.date_selector.last_30_days', from: new Date(year, month, day - 30), to: today},
      {label: 'metrics_top_bar.date_selector.last_3_months', from: new Date(year, month - 3, day), to: today},
      {label: 'metrics_top_bar.date_selector.last_6_months', from: new Date(year, month - 6, day), to: today},
      {label: 'metrics_top_bar.date_selector.all_time', from: new Date(2010, 1, 1), to: today}
    ];
  }.property(),
```

I'm not against using the "this.intl", however it feels a bit incoherent with how Ember works generally. It should not make any difference. Actually, I was even surprised by the usage, as my initial try was to use:

```hbs
{{format-message (intl-get range.label)}}
```

Ember typically distinguishes bound property and literal by the fact that it's unquoted or not.

**Comment by jasonmit** [comment] 2015-02-21 22:14
https://github.com/yahoo/ember-intl/pull/55 will resolve this but I'd like to write some tests for it before it's merged.

Feel free to test it out on my bound-intl-get branch

**Comment by bakura10** [comment] 2015-02-21 23:37
Thanks a lot! It makes things very coherent now :)

**Comment by jasonmit** [comment] 2015-02-22 04:10
I'll likely merge that PR Monday, but ping me if you discover any issues with 1.11-beta-* since I haven't tried to target them yet.

**Comment by bakura10** [comment] 2015-02-22 11:48
Hi,

I can confirm you that it is working as expected, even on 1.11. Thanks a lot :D.

**Closed** 2015-02-23 00:15 UTC
Labels: enhancement

**Comment by jasonmit** [comment] 2015-02-23 00:22
1.1.3 has been published with the fix.  Thanks again for the suggestion to add this :)
